### ISSUE TITLE
Redis password AUTH support

### ISSUE THREAD

**Issue by razvanphp** [carlosabalde/libvmod-redis#25]
How is this handled? I could just send this as a raw command, but then I do it for every request, and it makes no sense. Moving it in vcl_init() means that connection retries would need to be 0, right? otherwise after reconnect the password must be sent again.

It would be nice to have this documented.

Thank you!

**Comment by carlosabalde** [comment]
The VMOD currently does not support the ``AUTH`` command. As you suggest, providing a password should be part of the initializations executed during ``vcl_init`` phase. Otherwise, it's not really guaranteed that authentication is going to succeed, even when retries are disabled and using non-shared connections.

I think this is an interesting feature. I'm adding this to the TODO list. Thanks for the suggestion :)

**Comment by carlosabalde** [comment]
Authentication support added to the latest 4.0 and 4.1 releases: https://github.com/carlosabalde/libvmod-redis/releases/tag/4.1-0.3.5 and https://github.com/carlosabalde/libvmod-redis/releases/tag/4.0-0.3.5.

Implemented as a new parameter to the ``redis.db()`` object constructor.

**Comment by razvanphp** [comment]
Thank you very much for the fast solution. I will check this soon.
