### ISSUE TITLE
The commands and select db 

### ISSUE THREAD

**Issue by nagrgk** [carlosabalde/libvmod-redis#27]
how to select particular db index and run following command from varnish redis?

$count = $redis->eval('return table.getn(redis.call("keys", "PHPREDIS_SESSION:*"))');

thanks

**Comment by carlosabalde** [comment]
First of all, the VMOD does not support multiple database indexes. It always uses database 0. You could try to use the ``SELECT`` command on your own, but that's not safe due to how Redis connections are reused.

On the other hand, as a side note, beware that the ``KEYS`` command should never be used in a production server, specially when integrating Redis with a high performance caching proxy like Varnish Cache.
