### ISSUE TITLE
Support for IPv6 addresses and subnets

### ISSUE THREAD

**Issue by sagepe** [carlosabalde/libvmod-redis#46]
We've recently been testing this VMOD against a set of Redis and Sentinel hosts that are only available over IPv6 from Varnish (we're using this with Debian Bullseye and Varnish 6.5, but I think the below would apply for the current master branch, too).

IPv6 connectivty to Sentinel or Redis services when configured with DNS names appears to work fine, but we saw connection errors when trying to specify Redis servers using their IPv6 addresses (using the format `[::1]:6379`):

```
[REDIS][new_rcontext:882] Failed to establish connection (error=2, db=db, server=[<ipv6 addr>]:6379): Name or service not known
...
[REDIS][unsafe_discover_redis_server_role:994] Failed to establish role discovery connection (db=db, server=[<ipv6 addr>]:6379)
```
And similar errors when providing IPv6 addresses for Sentinel hosts:

```
[REDIS][unsafe_set_locations:652] Got error while parsing Sentinels (error=10, locations=[<ipv6 addr>]:26379, [<ipv6 addr>]:26379, [<ipv6 addr>]:26379)
```

Looking at the source code, I don't think that parsing IPv6 addresses and subnets is currently supported (although I'm not a C programmer).

In order to use the VMOD with sentinel it is necessary to configure the Redis servers using their IP addresses rather than their DNS names, so while it is possible to use the VMOD with IPv6-only standalone Redis servers, it doesn't seem possible currently to do so together with Sentinel (or, I assume, Redis Cluster).

Would you consider adding IPv6 support for addresses and subnets to the VMOD (assuming I'm correct in my assessment above)?

**Comment by carlosabalde** [comment]
IPv6 never received any attention in the implementation. In fact, it was explicitly ignored in some parts. I assume the underlying library has full IPv6 support, but I'm not even sure of that. I'll take a look at this, but no promisees at all about deadlines.

**Comment by carlosabalde** [comment]
I've spent a couple of hours looking at this. Conclusions:

- Part of the problem is the expected format is `::1:6379`, not `[::1]:6379`.
- Adding a single line fix I was able to pass almost all automated tests using IPv6 addresses everywhere. The only two tests breaking are related with the unpopular `.subnets()` feature. That one was originally limited to IPv4 and I'm not planning to change that.
- There are not automated tests for the Sentinel part, but it's obvious that's only supporting IPv4 addresses at the moment. It shouldn't be hard to improve that parsing.

**Comment by sagepe** [comment]
Thanks very much for looking at this so promptly!

Based on your comments above, I've configured Sentinels with hostnames and Redis servers with IP addresses in the format `::1:6379` and can confirm that does appear to work here; Varnish connects to the the Sentinels and the Redis servers successfully and picks up role changes from Sentinel, so that's great. I should have thought to test that format myself.

May I ask what the single line fix you mention was?

**Comment by carlosabalde** [comment]
This is the only change so far and it's only relevant when using Redis Cluster + IPv6:

```
diff --git a/src/core.c b/src/core.c
index e6aa04d..bc95ddc 100644
--- a/src/core.c
+++ b/src/core.c
@@ -90,9 +90,11 @@ new_redis_server(
     // Do not continue if this is a clustered database but the location is not
     // provided using the IP + port format.
     struct in_addr ia4;
+    struct in6_addr ia6;
     if ((db->cluster.enabled) &&
         ((result->location.type != REDIS_SERVER_LOCATION_HOST_TYPE) ||
-         (inet_pton(AF_INET, result->location.parsed.address.host, &ia4) == 0))) {
+         ((inet_pton(AF_INET, result->location.parsed.address.host, &ia4) == 0) &&
+          (inet_pton(AF_INET6, result->location.parsed.address.host, &ia6) == 0)))) {
         free((void *) result->location.parsed.address.host);
         FREE_OBJ(result);
         return NULL;
```

However, for full IPv6 support (`.subnets()`excluded), some work is also needed to fix this naïve parsing:

https://github.com/carlosabalde/libvmod-redis/blob/51870418149bc6fde3d3e05bb573369c4c575950/src/sentinel.c#L597-L638

This is not affecting your tests because you're using host names for sentinels. I'll try to fix that as soon as I can find some time to work on this.
